name: Deploy Docker Image to Github

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
    - name: checkout Code
      uses: actions/checkout@v4
    - name: build image
      run: docker build -t mynginx .
    - name: tag image
      run: docker tag mynginx:latest ghcr.io/nattapong254/mynginx:v1
    - name: deploy
      run: docker push ghcr.io/nattapong254/mynginx:v1
